# Generated by Django 4.2.5 on 2023-10-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50)),
                ('detalle_corto', models.CharField(max_length=50)),
                ('tipo', models.TextField(choices=[('S', 'Suspencion de actividades'), ('C', 'Suspencion de clase'), ('I', 'Informacion')], max_length=1)),
                ('visible', models.BooleanField()),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_ultima_publicacion', models.DateTimeField()),
                ('Entidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.entidad')),
            ],
        ),
    ]
