# Generated by Django 4.2.5 on 2023-10-23 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0002_comunicado_modificado_por_comunicado_publicado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='publicado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
