# Generated by Django 4.2.5 on 2023-10-24 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_alter_comunicado_publicado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
    ]
